### PR TITLE
change focus color light blue to dark blue

### PR DESCRIPTION
**Pull request by nnat425**
- Changing the focus color of global search via requested ticket WWW-494.

### CODE REVIEW

**Comment by ktp242** [comment]
Looks nice!

There are just tow things I noticed.

1. the focus border is still light blue surrounding tabs.
2. on mobile view, the result items do not have focus circle.

**Comment by nnat425** [comment]
1. Good catch on the tabs, will change that now. 
2. I'll double check that now.

**Comment by nnat425** [comment]
Notes: 
Talked to Willa and Jack. 
1. On active tab, there will be a light blue border 
2. On non active tab, there will be a dark blue border 
3. Hover of search button, there will be a light blue order

**Comment by jackkim9** [comment]
@nnat425 (and @ktp242),

@wlla and I just spoke about the light focus color in the active tab.

We recommend the current light blue color on the active tab AND search button and dark navy focus color on the rest of the page.

(Separately, the hover states should follow the specs in https://jira.nypl.org/browse/WWW-554.)

**Comment by ktp242** [comment]
I have some new discoveries!

1. On mobile view, the tab dropdown menu does not have a focus circle.
2. On mobile view, the results items don't seem to have focus circle.
3. On desktop view, the results items will be focused on the image if they have  one, if no, they will be focused on the texts. I think it has something to do with the HTML structure.

**Comment by nnat425** [comment]
@ktp242 taking a look now at 1 & 2.

For number 3, if a result item has an image, the focused/dark blue box is surrounding the image and title. Are you getting the same result? If so, that's the expected behavior we want.

**Comment by jackkim9** [comment]
3 is an expected behavior (by @wlla  and me).

**Comment by ktp242** [comment]
Yes for 3 that's what I am getting! And then it is not an issue! yay

**Comment by ktp242** [comment]
Hi hi I still don't see the focus circle on case 1 and case 2. Are you still working on it?

**Comment by nnat425** [comment]
@ktp242 @LucasCioffi @danamansana ready for another look. Thanks.

**Comment by ktp242** [comment]
Nice! you made it! The result items now are nicely focused!!!!!

Just a question that do we need to care about the search input field and the link for previous tool in this PR? Because their focus are not styled yet.

**Comment by nnat425** [comment]
@ktp242 adding those changes now.

**Pull request merged**
