### PR TITLE
Align layout to lion and clean up style

### PR DESCRIPTION
**Pull request by jackkim9**
- Addresses WWW-558 Align page elements with lion (not logotype)
screen shot 2018-12-11 at 4 56 16 pm

- Addresses WWW-547 Search Style Clean up - Phase 1
[No screenshot but see above: this is just an overall margin/type size clean up]

- Removes styling for "BETA" in prep for it's removal
screen shot 2018-12-11 at 4 56 59 pm

- Creates a mixin for accessibility focus border
screen shot 2018-12-11 at 4 57 32 pm

### CODE REVIEW

**Comment by jackkim9** [comment]
Thanks @LucasCioffi, addressed your comment.
screen shot 2018-12-11 at 6 12 10 pm
screen shot 2018-12-11 at 6 12 03 pm

**Comment by ktp242** [comment]
1. Not sure if it is in the scope of this PR, or needs to be fixed, but I saw the first image reaches to the dividing line with no space in between. Please see the screen shot here


screen shot 2018-12-11 at 6 30 10 pm


2. On mobile the result items lose their focus circles

**Comment by ktp242** [comment]
Good fix!!!

But I saw another issue here
http://nypl-global-search-development.us-east-1.elasticbeanstalk.com/search/beer/exhibitions

If you tab to the second result item on mobile view, you won't see the focus circle.

**Comment by jackkim9** [comment]
I'm closing this PR @nnat425 @ktp242

**Pull request closed without merging**
