### PR TITLE
[Bug] Overlapping summary text

### PR DESCRIPTION
**Pull request by jackkim9**
Primarily fixes https://jira.nypl.org/browse/WWW-579.

Before
screen shot 2018-12-13 at 11 54 03 am

After
screen shot 2018-12-13 at 11 54 44 am

screen shot 2018-12-13 at 11 55 30 am

### CODE REVIEW

**Comment by ktp242** [comment]
Is this update on development server already?
http://nypl-global-search-development.us-east-1.elasticbeanstalk.com/search/wine/locations

I don't really see the issue on there.

**Comment by jackkim9** [comment]
Hmm not sure. It's in QA
https://qa-www.nypl.org/search/hello/

**Comment by ktp242** [comment]
Got it! Ok let me put the updates to development server now

**Comment by nnat425** [comment]
Lets merge it and see.

**Pull request merged**
