### PR TITLE
Fix mobile dropdown bugs

### PR DESCRIPTION
**Pull request by nnat425**
- Point of this PR is to accomplish the following:

When choosing a value from the dropdown or selecting a value from the tab, when switching to viewports from desktop to mobile or mobile to desktop, the same results show as well as the the value selected by the user.

### CODE REVIEW

**Comment by nnat425** [comment]
@ktp242 Confirming we can close this pull request because you've added these changes to another  PR already. Please confirm @ktp242. Thanks.

**Comment by ktp242** [comment]
I think this PR is not needed? Since the changes are manually added to this PR
https://github.com/NYPL/dgx-global-search/pull/90

**Comment by nnat425** [comment]
This can be closed then. I haven’t look at PR at 90 yet so I personally
can’t confirm.

**Comment by nnat425** [comment]
Pull request #90 , includes the changes on this PR.

**Pull request closed without merging**
