### PR TITLE
search results ui polish

### PR DESCRIPTION
**Pull request by jackkim9**
Minor style polish to reduce the gap between design and implementation.

Addresses WWW-513 (right-align the search image) and WWW-548 (search results style polish).

### CODE REVIEW

**Comment by ktp242** [comment]
It looks great! Thanks for doing this.
I only found on minor issue happens from width 1024px to about 1050px (IPad portrait). The right edge of the facets will be on the edge of the page or be cut.

Please see the screenshots below,

screen shot 2018-12-04 at 4 48 38 pm
screen shot 2018-12-04 at 4 46 45 pm

**Comment by jackkim9** [comment]
Thank you, @ktp242 ! I believe that's a known issue @nnat425 has been addressing in https://github.com/NYPL/dgx-global-search/pull/75

CC: @chrismulholland

**Comment by ktp242** [comment]
I checked on QA, and the similar issue happens from 1128px to 1159px.

**Comment by jackkim9** [comment]
Thanks. Correct. Those are the only issues addressed in this PR.

**Comment by nnat425** [comment]
In the newest PR, I fixed the tab overflow issue. @jackkim9 @ktp242 @LucasCioffi

**Pull request merged**
